/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ContEmpleados;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.sql.ResultSet;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class FrmEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmpleados
     */
    DefaultTableModel Modelo;
    public FrmEmpleados() {
        initComponents();
        //cargar datos
        String[] Titulos = {"Id_Empleado", "Apellidos_Empleado", "Nombres_Empleado", "Fecha_Nac", "Direccion", "NIT",
            "Tipo_Documento","Documento", "Genero", "Estado_Civil", "Empresa" };
        Modelo = new DefaultTableModel(null, Titulos);
        TbEmpleados.setModel(Modelo);
        CargarTabla();
        //👆
    }
    void CargarTabla() {
        while (Modelo.getRowCount() > 0) {
            Modelo.removeRow(0);
        }
        try{
        ResultSet rs = ContEmpleados.CargarEmpleado();
            while (rs.next()) {
                Object[] Valores = {rs.getString("Id_Empleado"), rs.getString("Apellidos_Empleado"), rs.getString("Nombres_Empleado"), rs.getString("Fecha_Nac"), rs.getString("Direccion"), rs.getString("NIT"),
                    rs.getString("Tipo_Documento"), rs.getString("Documento"), rs.getString("Genero"), rs.getString("Estado_Civil"),  rs.getString("Empresa") };
                Modelo.addRow(Valores);
            }
        } catch (Exception e) {
        }
    }
    void CargarTipoDocumento(){
        CmbTipoDoc.removeAllItems();
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DtChNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaDireccion = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnLista = new Validaciones.BotonRedondo();
        BtnActualizar = new Validaciones.BotonRedondo();
        BtnEliminar = new Validaciones.BotonRedondo();
        jLabel11 = new javax.swing.JLabel();
        CmbEmpresa = new javax.swing.JComboBox<>();
        CmbGenero = new javax.swing.JComboBox<>();
        CmbTipoDoc = new javax.swing.JComboBox<>();
        CmbEstadocivil = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        BtnLimpiarCampos = new Validaciones.BotonRedondo();
        BtnAgregar = new Validaciones.BotonRedondo();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tipo de documento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombres completos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellidos completos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Documento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha de nacimiento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NIT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        DtChNacimiento.setBackground(new java.awt.Color(236, 245, 250));
        DtChNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        DtChNacimiento.setToolTipText("");
        DtChNacimiento.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(DtChNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Genero");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Dirección");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        TxtAreaDireccion.setBackground(new java.awt.Color(236, 245, 250));
        TxtAreaDireccion.setColumns(20);
        TxtAreaDireccion.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        TxtAreaDireccion.setRows(5);
        jScrollPane1.setViewportView(TxtAreaDireccion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 250, 90));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Estado Civil");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Telefono principal");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        BtnLista.setBackground(new java.awt.Color(144, 224, 239));
        BtnLista.setForeground(new java.awt.Color(83, 83, 83));
        BtnLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus +_20px.png"))); // NOI18N
        BtnLista.setText("Lista");
        BtnLista.setToolTipText("");
        BtnLista.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnLista.setColor(new java.awt.Color(144, 224, 239));
        BtnLista.setColorClick(new java.awt.Color(0, 204, 204));
        BtnLista.setColorOver(new java.awt.Color(0, 204, 204));
        BtnLista.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnLista.setRadius(40);
        BtnLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnListaMouseClicked(evt);
            }
        });
        getContentPane().add(BtnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 190, 50));

        BtnActualizar.setBackground(new java.awt.Color(144, 224, 239));
        BtnActualizar.setForeground(new java.awt.Color(83, 83, 83));
        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_20px.png"))); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setToolTipText("");
        BtnActualizar.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnActualizar.setColor(new java.awt.Color(144, 224, 239));
        BtnActualizar.setColorClick(new java.awt.Color(0, 204, 204));
        BtnActualizar.setColorOver(new java.awt.Color(0, 204, 204));
        BtnActualizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnActualizar.setRadius(40);
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        getContentPane().add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 190, 50));

        BtnEliminar.setBackground(new java.awt.Color(144, 224, 239));
        BtnEliminar.setForeground(new java.awt.Color(83, 83, 83));
        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/broom_20px.png"))); // NOI18N
        BtnEliminar.setText("Eliminar Empleado");
        BtnEliminar.setToolTipText("");
        BtnEliminar.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnEliminar.setColor(new java.awt.Color(144, 224, 239));
        BtnEliminar.setColorClick(new java.awt.Color(0, 204, 204));
        BtnEliminar.setColorOver(new java.awt.Color(0, 204, 204));
        BtnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnEliminar.setRadius(40);
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 190, 50));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Empresa");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        CmbEmpresa.setBackground(new java.awt.Color(236, 245, 250));
        CmbEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CmbEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        CmbEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CmbEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 250, 30));

        CmbGenero.setBackground(new java.awt.Color(236, 245, 250));
        CmbGenero.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CmbGenero.setForeground(new java.awt.Color(0, 0, 0));
        CmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 250, 30));

        CmbTipoDoc.setBackground(new java.awt.Color(236, 245, 250));
        CmbTipoDoc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CmbTipoDoc.setForeground(new java.awt.Color(0, 0, 0));
        CmbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbTipoDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbTipoDocMouseClicked(evt);
            }
        });
        getContentPane().add(CmbTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 250, 30));

        CmbEstadocivil.setBackground(new java.awt.Color(236, 245, 250));
        CmbEstadocivil.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CmbEstadocivil.setForeground(new java.awt.Color(0, 0, 0));
        CmbEstadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CmbEstadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 250, 30));

        jTextField2.setBackground(new java.awt.Color(236, 245, 250));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 30));

        jTextField3.setBackground(new java.awt.Color(236, 245, 250));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 250, 30));

        jTextField4.setBackground(new java.awt.Color(236, 245, 250));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 250, 30));

        jTextField5.setBackground(new java.awt.Color(236, 245, 250));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 30));

        jTextField6.setBackground(new java.awt.Color(236, 245, 250));
        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 250, 30));

        BtnLimpiarCampos.setBackground(new java.awt.Color(144, 224, 239));
        BtnLimpiarCampos.setForeground(new java.awt.Color(83, 83, 83));
        BtnLimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/broom_20px.png"))); // NOI18N
        BtnLimpiarCampos.setText("Limpiar Campos");
        BtnLimpiarCampos.setToolTipText("");
        BtnLimpiarCampos.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnLimpiarCampos.setColor(new java.awt.Color(144, 224, 239));
        BtnLimpiarCampos.setColorClick(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos.setColorOver(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnLimpiarCampos.setRadius(40);
        BtnLimpiarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLimpiarCamposMouseClicked(evt);
            }
        });
        getContentPane().add(BtnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 190, 50));

        BtnAgregar.setBackground(new java.awt.Color(144, 224, 239));
        BtnAgregar.setForeground(new java.awt.Color(83, 83, 83));
        BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus +_20px.png"))); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.setToolTipText("");
        BtnAgregar.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnAgregar.setColor(new java.awt.Color(144, 224, 239));
        BtnAgregar.setColorClick(new java.awt.Color(0, 204, 204));
        BtnAgregar.setColorOver(new java.awt.Color(0, 204, 204));
        BtnAgregar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnAgregar.setRadius(40);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        getContentPane().add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 190, 50));

        TbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TbEmpleados);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 860, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnListaMouseClicked

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizarMouseClicked

    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarMouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void BtnLimpiarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarCamposMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarCamposMouseClicked

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
       // GuardarUsuario();
        CargarTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void CmbTipoDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbTipoDocMouseClicked
         
// TODO add your handling code here:
    }//GEN-LAST:event_CmbTipoDocMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   try {
             UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        UIManager.put( "Button.arc", 999 );
        UIManager.put( "Component.arc", 999 );
        UIManager.put( "ProgressBar.arc", 999 );
        UIManager.put( "TextComponent.arc", 999 );
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Validaciones.BotonRedondo BtnActualizar;
    public Validaciones.BotonRedondo BtnAgregar;
    public Validaciones.BotonRedondo BtnEliminar;
    public Validaciones.BotonRedondo BtnLimpiarCampos;
    public Validaciones.BotonRedondo BtnLista;
    public javax.swing.JComboBox<String> CmbEmpresa;
    public javax.swing.JComboBox<String> CmbEstadocivil;
    public javax.swing.JComboBox<String> CmbGenero;
    public javax.swing.JComboBox<String> CmbTipoDoc;
    public com.toedter.calendar.JDateChooser DtChNacimiento;
    private javax.swing.JTable TbEmpleados;
    public javax.swing.JTextArea TxtAreaDireccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
