
package Vista;
    import Controlador.ContLogin;
    import Controlador.ContConexion;
import Controlador.ContConfiguracion;
    import java.awt.Color;
    import java.awt.Dimension;
    import java.awt.Toolkit;
    import java.awt.geom.RoundRectangle2D;
import java.io.File;
    import javax.swing.JOptionPane;
    import java.sql.Connection;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public  FrmLogin() {
         setUndecorated(true);
                
        initComponents();
        LeerArchivo();
        //aliniar al centro
        setLocationRelativeTo(null);
        //
        
        //Redondear 
        
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),50,50));
        ////----------------------------------
        Toolkit t = Toolkit.getDefaultToolkit();
        
        Dimension screemSize = t.getScreenSize();
        
        int ancho = screemSize.width;
        int alto = screemSize.height;
        
        setBounds(0,0,  800, 475);
        
        this.setLocationRelativeTo(null);
        
        //Crear atributos
    
    }
 void LeerArchivo(){
        try {
            Scanner input = new Scanner(new File("C://Users/pc/OneDrive/Documentos/NetBeansProjects/Expo_2022/Cuidados_Medicos/dist/lib/sysconfig.txt"));
            
            int i = 0;
            while (input.hasNextLine()){
                String line = input.nextLine(); 
                switch(i){
                    case 0:
                        ContConfiguracion.IP = line;
                        break;
                    case 1:
                        ContConfiguracion.Port = line;
                        break;
                    case 2:
                        ContConfiguracion.Database = line;
                        break;
                    case 3:
                        ContConfiguracion.User = line;
                        break;
                    case 4:
                        ContConfiguracion.Password = line;
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Error en la lectura");
                        break;  
                }
                i++;
            }
            input.close();
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PnlMenuMover1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ImgLogin = new javax.swing.JLabel();
        LblSalir = new javax.swing.JLabel();
        PnlMenuMover = new javax.swing.JPanel();
        BtnIniciarSecion = new Validaciones.BotonRedondo();
        TxtClave = new jtextfieldround.JPasswordFieldRound();
        TxtNombreUsuario = new jtextfieldround.JTextFieldRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnOlvideContraseña = new javax.swing.JLabel();
        LblConfiguracionDB = new javax.swing.JLabel();
        LblTest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(144, 224, 239));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Sin título-1 (1).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 40, 400, 475);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Squiggles - Colorful (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 480);

        PnlMenuMover1.setBackground(new java.awt.Color(144, 224, 239));
        PnlMenuMover1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PnlMenuMover1MouseDragged(evt);
            }
        });
        jPanel1.add(PnlMenuMover1);
        PnlMenuMover1.setBounds(0, 0, 400, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 475));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(102, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 199, 255));
        jLabel2.setText("Iniciar Sesion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, -1));

        ImgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logo.png"))); // NOI18N
        jPanel2.add(ImgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 130, 130));

        LblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/door_closed_30px.png"))); // NOI18N
        LblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblSalirMouseExited(evt);
            }
        });
        jPanel2.add(LblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, 30));

        PnlMenuMover.setBackground(new java.awt.Color(255, 255, 255));
        PnlMenuMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PnlMenuMoverMouseDragged(evt);
            }
        });
        PnlMenuMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PnlMenuMoverMousePressed(evt);
            }
        });
        jPanel2.add(PnlMenuMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        BtnIniciarSecion.setBackground(new java.awt.Color(144, 224, 239));
        BtnIniciarSecion.setForeground(new java.awt.Color(83, 83, 83));
        BtnIniciarSecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Check Circle_20px.png"))); // NOI18N
        BtnIniciarSecion.setText("Continuar");
        BtnIniciarSecion.setToolTipText("");
        BtnIniciarSecion.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnIniciarSecion.setColor(new java.awt.Color(144, 224, 239));
        BtnIniciarSecion.setColorClick(new java.awt.Color(0, 204, 204));
        BtnIniciarSecion.setColorOver(new java.awt.Color(0, 204, 204));
        BtnIniciarSecion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnIniciarSecion.setRadius(40);
        BtnIniciarSecion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIniciarSecionMouseClicked(evt);
            }
        });
        BtnIniciarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarSecionActionPerformed(evt);
            }
        });
        jPanel2.add(BtnIniciarSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 170, 50));

        TxtClave.setText("Clave o Contraseña");
        TxtClave.setBackground(new java.awt.Color(144, 224, 239));
        TxtClave.setCaretColor(new java.awt.Color(0, 0, 0));
        TxtClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtClaveMousePressed(evt);
            }
        });
        jPanel2.add(TxtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 350, 40));

        TxtNombreUsuario.setText("Nombre de Usuario");
        TxtNombreUsuario.setBackground(new java.awt.Color(144, 224, 239));
        TxtNombreUsuario.setCaretColor(new java.awt.Color(0, 0, 0));
        TxtNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtNombreUsuarioMousePressed(evt);
            }
        });
        jPanel2.add(TxtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 350, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 199, 255));
        jLabel5.setText("Nombre de Usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 199, 255));
        jLabel6.setText("Contraseña");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        BtnOlvideContraseña.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnOlvideContraseña.setForeground(new java.awt.Color(153, 153, 153));
        BtnOlvideContraseña.setText("¿olvidaste tu contraseña?");
        BtnOlvideContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(BtnOlvideContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        LblConfiguracionDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_database_20px.png"))); // NOI18N
        LblConfiguracionDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblConfiguracionDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblConfiguracionDBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblConfiguracionDBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblConfiguracionDBMouseExited(evt);
            }
        });
        jPanel2.add(LblConfiguracionDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 30));

        LblTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_database_20px.png"))); // NOI18N
        LblTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblTestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblTestMouseExited(evt);
            }
        });
        jPanel2.add(LblTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblSalirMouseClicked
    int confirmar = JOptionPane.showConfirmDialog(null, "¿Estas seguro que quieres salir?");
        if(confirmar == JOptionPane.YES_OPTION)
        {
            System.exit(0); 
        }            
// TODO add your handling code here:
    }//GEN-LAST:event_LblSalirMouseClicked
int xMouse, yMouse;
    private void PnlMenuMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlMenuMoverMousePressed
      xMouse = evt.getX();
        yMouse = evt.getY(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_PnlMenuMoverMousePressed

    private void PnlMenuMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlMenuMoverMouseDragged
int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);          
// TODO add your handling code here:
    }//GEN-LAST:event_PnlMenuMoverMouseDragged

    private void PnlMenuMover1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlMenuMover1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);// TODO add your handling code here:
    }//GEN-LAST:event_PnlMenuMover1MouseDragged

    private void TxtNombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNombreUsuarioMousePressed
 if(TxtNombreUsuario.getText().equals("Nombre de Usuario")){
            TxtNombreUsuario.setText("");
            TxtNombreUsuario.setForeground(Color.BLACK);
            
        }
        if(String.valueOf(TxtClave.getPassword()).isEmpty()){
        TxtClave.setText("Clave o Contraseña");
        TxtClave.setForeground(new Color(153,153,153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreUsuarioMousePressed

    private void TxtClaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtClaveMousePressed
       if(String.valueOf(TxtClave.getPassword()).equals("Clave o Contraseña")){
       TxtClave.setText(""); 
       TxtClave.setForeground(Color.black); 
               TxtClave.setEchoChar('\u25cf');

       }
       if(TxtNombreUsuario.getText().isEmpty()){
       TxtNombreUsuario.setText("Nombre de Usuario");
       TxtNombreUsuario.setForeground(new Color(153,153,153));
       }     
       // TODO add your handling code here:
    }//GEN-LAST:event_TxtClaveMousePressed

    private void BtnIniciarSecionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIniciarSecionMouseClicked
ContLogin clog = new ContLogin();

        if (TxtNombreUsuario.getText().equals("")||TxtClave.getText().equals("")||
                TxtNombreUsuario.getText().equals("Nombre de Usuario")||TxtClave.getText().equals("Clave o Contraseña")) {
            JOptionPane.showMessageDialog(null, "Campos vacios", "Error de proceso", JOptionPane.WARNING_MESSAGE);
        }else{
            String Clave = ContLogin.getMD5(TxtClave.getText());  
            ContLogin.usuario = TxtNombreUsuario.getText();
            clog.password = Clave;
            int respuesta = clog.ValidarLogin();
            
            if (respuesta == 1) {
               FrmPrincipal next = new FrmPrincipal();
               next.setVisible(true);
               this.dispose();
            }
            else{
                
                JOptionPane.showMessageDialog(null,"Credenciales incorrectas");
                
            }    // TODO add your handling code here:
        }
    }//GEN-LAST:event_BtnIniciarSecionMouseClicked
    public void changeimg(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon (getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    private void LblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblSalirMouseEntered
           
            changeimg(LblSalir, "/Icon/open_door_30px.png");        
// TODO add your handling code here:
    }//GEN-LAST:event_LblSalirMouseEntered

    private void LblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblSalirMouseExited
        changeimg(LblSalir, "/Icon/door_closed_30px.png"); 
// TODO add your handling code here:
    }//GEN-LAST:event_LblSalirMouseExited

    private void LblConfiguracionDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblConfiguracionDBMouseClicked
FrmConfiguracion next = new FrmConfiguracion();
            next.setVisible(true);
            //this.dispose(); /*ocultar*/      
            // TODO add your handling code here:
    }//GEN-LAST:event_LblConfiguracionDBMouseClicked

    private void LblConfiguracionDBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblConfiguracionDBMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LblConfiguracionDBMouseEntered

    private void LblConfiguracionDBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblConfiguracionDBMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LblConfiguracionDBMouseExited

    private void LblTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblTestMouseClicked
        if (ContConexion.getConnectionController()!=null) {
                    JOptionPane.showMessageDialog(null, "Conexión existosa. ");
                }   
           // TODO add your handling code here:
    }//GEN-LAST:event_LblTestMouseClicked

    private void LblTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblTestMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LblTestMouseEntered

    private void LblTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblTestMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LblTestMouseExited

    private void BtnIniciarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarSecionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIniciarSecionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Validaciones.BotonRedondo BtnIniciarSecion;
    private javax.swing.JLabel BtnOlvideContraseña;
    private javax.swing.JLabel ImgLogin;
    private javax.swing.JLabel LblConfiguracionDB;
    private javax.swing.JLabel LblSalir;
    private javax.swing.JLabel LblTest;
    private javax.swing.JPanel PnlMenuMover;
    private javax.swing.JPanel PnlMenuMover1;
    private jtextfieldround.JPasswordFieldRound TxtClave;
    private jtextfieldround.JTextFieldRound TxtNombreUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
