/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author pc
 */
public class JPanlHome extends javax.swing.JPanel {

    /** Creates new form JPanlHome */
    public JPanlHome() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel3 = new Validaciones.RoundedPanel();
        roundedPanel4 = new Validaciones.RoundedPanel();
        roundedPanel5 = new Validaciones.RoundedPanel();
        roundedPanel6 = new Validaciones.RoundedPanel();
        roundedPanel7 = new Validaciones.RoundedPanel();
        roundedPanel8 = new Validaciones.RoundedPanel();
        roundedPanel9 = new Validaciones.RoundedPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel3.setBackground(new java.awt.Color(144, 224, 239));
        roundedPanel3.setForeground(new java.awt.Color(144, 224, 239));
        roundedPanel3.setRoundBottomLeft(40);
        roundedPanel3.setRoundBottomRight(40);
        roundedPanel3.setRoundTopLeft(40);
        roundedPanel3.setRoundTopRight(40);

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        add(roundedPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 510, 310));

        roundedPanel4.setBackground(new java.awt.Color(144, 224, 239));
        roundedPanel4.setForeground(new java.awt.Color(144, 224, 239));
        roundedPanel4.setRoundBottomLeft(40);
        roundedPanel4.setRoundBottomRight(40);
        roundedPanel4.setRoundTopLeft(40);
        roundedPanel4.setRoundTopRight(40);

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(roundedPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 150));

        roundedPanel5.setBackground(new java.awt.Color(144, 224, 239));
        roundedPanel5.setForeground(new java.awt.Color(144, 224, 239));
        roundedPanel5.setRoundBottomLeft(40);
        roundedPanel5.setRoundBottomRight(40);
        roundedPanel5.setRoundTopLeft(40);
        roundedPanel5.setRoundTopRight(40);

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(roundedPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        roundedPanel6.setBackground(new java.awt.Color(144, 224, 239));
        roundedPanel6.setForeground(new java.awt.Color(144, 224, 239));
        roundedPanel6.setRoundBottomLeft(40);
        roundedPanel6.setRoundBottomRight(40);
        roundedPanel6.setRoundTopLeft(40);
        roundedPanel6.setRoundTopRight(40);

        javax.swing.GroupLayout roundedPanel6Layout = new javax.swing.GroupLayout(roundedPanel6);
        roundedPanel6.setLayout(roundedPanel6Layout);
        roundedPanel6Layout.setHorizontalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        roundedPanel6Layout.setVerticalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(roundedPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        roundedPanel7.setBackground(new java.awt.Color(144, 224, 239));
        roundedPanel7.setForeground(new java.awt.Color(144, 224, 239));
        roundedPanel7.setRoundBottomLeft(40);
        roundedPanel7.setRoundBottomRight(40);
        roundedPanel7.setRoundTopLeft(40);
        roundedPanel7.setRoundTopRight(40);

        javax.swing.GroupLayout roundedPanel7Layout = new javax.swing.GroupLayout(roundedPanel7);
        roundedPanel7.setLayout(roundedPanel7Layout);
        roundedPanel7Layout.setHorizontalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        roundedPanel7Layout.setVerticalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(roundedPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        roundedPanel8.setBackground(new java.awt.Color(144, 224, 239));
        roundedPanel8.setForeground(new java.awt.Color(144, 224, 239));
        roundedPanel8.setRoundBottomLeft(40);
        roundedPanel8.setRoundBottomRight(40);
        roundedPanel8.setRoundTopLeft(40);
        roundedPanel8.setRoundTopRight(40);

        javax.swing.GroupLayout roundedPanel8Layout = new javax.swing.GroupLayout(roundedPanel8);
        roundedPanel8.setLayout(roundedPanel8Layout);
        roundedPanel8Layout.setHorizontalGroup(
            roundedPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        roundedPanel8Layout.setVerticalGroup(
            roundedPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        add(roundedPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 560, 260));

        roundedPanel9.setBackground(new java.awt.Color(144, 224, 239));
        roundedPanel9.setForeground(new java.awt.Color(144, 224, 239));
        roundedPanel9.setRoundBottomLeft(40);
        roundedPanel9.setRoundBottomRight(40);
        roundedPanel9.setRoundTopLeft(40);
        roundedPanel9.setRoundTopRight(40);

        javax.swing.GroupLayout roundedPanel9Layout = new javax.swing.GroupLayout(roundedPanel9);
        roundedPanel9.setLayout(roundedPanel9Layout);
        roundedPanel9Layout.setHorizontalGroup(
            roundedPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        roundedPanel9Layout.setVerticalGroup(
            roundedPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        add(roundedPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 280, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Validaciones.RoundedPanel roundedPanel3;
    private Validaciones.RoundedPanel roundedPanel4;
    private Validaciones.RoundedPanel roundedPanel5;
    private Validaciones.RoundedPanel roundedPanel6;
    private Validaciones.RoundedPanel roundedPanel7;
    private Validaciones.RoundedPanel roundedPanel8;
    private Validaciones.RoundedPanel roundedPanel9;
    // End of variables declaration//GEN-END:variables

}
