/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author pc
 */
public class JPanlPlanesTrabajo extends javax.swing.JPanel {

    /**
     * Creates new form JPanlPlanesTrabajo
     */
    public JPanlPlanesTrabajo() {
        initComponents();
        FlatLightLaf.setup();
        try {
             UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        UIManager.put( "Button.arc", 999 );
        UIManager.put( "Component.arc", 999 );
        UIManager.put( "ProgressBar.arc", 999 );
        UIManager.put( "TextComponent.arc", 999 );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtBuscar = new jtextfieldround.JTextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        LblTItulo = new javax.swing.JLabel();
        LblTItulo1 = new javax.swing.JLabel();
        BtnHorarioEmpleado = new Validaciones.BotonRedondo();
        BtnPlanesEmpleado = new Validaciones.BotonRedondo();
        BtnHorarioAplicaciones = new Validaciones.BotonRedondo();
        BtnAsignacionContratos = new Validaciones.BotonRedondo();
        roundedPanel1 = new Validaciones.RoundedPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        BtnAgregar = new Validaciones.BotonRedondo();
        BtnActualizar = new Validaciones.BotonRedondo();
        BtnLimpiarCampos1 = new Validaciones.BotonRedondo();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel2 = new Validaciones.RoundedPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        BtnAgregar2 = new Validaciones.BotonRedondo();
        BtnActualizar2 = new Validaciones.BotonRedondo();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        BtnLimpiarCampos3 = new Validaciones.BotonRedondo();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtBuscar.setText("Ingrese el nombre del usuario a buscar");
        TxtBuscar.setBackground(new java.awt.Color(236, 245, 250));
        TxtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 570, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search_20px.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, 30));

        LblTItulo.setBackground(new java.awt.Color(83, 83, 83));
        LblTItulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LblTItulo.setForeground(new java.awt.Color(0, 0, 0));
        LblTItulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblTItulo.setText("Planes de trabajo");
        LblTItulo.setToolTipText("");
        LblTItulo.setPreferredSize(new java.awt.Dimension(100, 19));
        add(LblTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, -1));

        LblTItulo1.setBackground(new java.awt.Color(83, 83, 83));
        LblTItulo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LblTItulo1.setForeground(new java.awt.Color(0, 0, 0));
        LblTItulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblTItulo1.setText("Planes de trabajo");
        LblTItulo1.setToolTipText("");
        LblTItulo1.setPreferredSize(new java.awt.Dimension(100, 19));
        add(LblTItulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 140, -1));

        BtnHorarioEmpleado.setBackground(new java.awt.Color(144, 224, 239));
        BtnHorarioEmpleado.setForeground(new java.awt.Color(83, 83, 83));
        BtnHorarioEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Check Circle_20px.png"))); // NOI18N
        BtnHorarioEmpleado.setText("Horario  empleados");
        BtnHorarioEmpleado.setToolTipText("");
        BtnHorarioEmpleado.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnHorarioEmpleado.setColor(new java.awt.Color(144, 224, 239));
        BtnHorarioEmpleado.setColorClick(new java.awt.Color(0, 204, 204));
        BtnHorarioEmpleado.setColorOver(new java.awt.Color(0, 204, 204));
        BtnHorarioEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnHorarioEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnHorarioEmpleado.setRadius(50);
        BtnHorarioEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHorarioEmpleadoMouseClicked(evt);
            }
        });
        add(BtnHorarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 210, 50));

        BtnPlanesEmpleado.setBackground(new java.awt.Color(144, 224, 239));
        BtnPlanesEmpleado.setForeground(new java.awt.Color(83, 83, 83));
        BtnPlanesEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Check Circle_20px.png"))); // NOI18N
        BtnPlanesEmpleado.setText("Planes  empleados");
        BtnPlanesEmpleado.setToolTipText("");
        BtnPlanesEmpleado.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnPlanesEmpleado.setColor(new java.awt.Color(144, 224, 239));
        BtnPlanesEmpleado.setColorClick(new java.awt.Color(0, 204, 204));
        BtnPlanesEmpleado.setColorOver(new java.awt.Color(0, 204, 204));
        BtnPlanesEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnPlanesEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnPlanesEmpleado.setRadius(50);
        BtnPlanesEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPlanesEmpleadoMouseClicked(evt);
            }
        });
        add(BtnPlanesEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 210, 50));

        BtnHorarioAplicaciones.setBackground(new java.awt.Color(144, 224, 239));
        BtnHorarioAplicaciones.setForeground(new java.awt.Color(83, 83, 83));
        BtnHorarioAplicaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Check Circle_20px.png"))); // NOI18N
        BtnHorarioAplicaciones.setText("Horario  aplicaciones");
        BtnHorarioAplicaciones.setToolTipText("");
        BtnHorarioAplicaciones.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnHorarioAplicaciones.setColor(new java.awt.Color(144, 224, 239));
        BtnHorarioAplicaciones.setColorClick(new java.awt.Color(0, 204, 204));
        BtnHorarioAplicaciones.setColorOver(new java.awt.Color(0, 204, 204));
        BtnHorarioAplicaciones.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnHorarioAplicaciones.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnHorarioAplicaciones.setRadius(50);
        BtnHorarioAplicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHorarioAplicacionesMouseClicked(evt);
            }
        });
        add(BtnHorarioAplicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 210, 50));

        BtnAsignacionContratos.setBackground(new java.awt.Color(144, 224, 239));
        BtnAsignacionContratos.setForeground(new java.awt.Color(83, 83, 83));
        BtnAsignacionContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Check Circle_20px.png"))); // NOI18N
        BtnAsignacionContratos.setText("Asignación de contratos");
        BtnAsignacionContratos.setToolTipText("");
        BtnAsignacionContratos.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnAsignacionContratos.setColor(new java.awt.Color(144, 224, 239));
        BtnAsignacionContratos.setColorClick(new java.awt.Color(0, 204, 204));
        BtnAsignacionContratos.setColorOver(new java.awt.Color(0, 204, 204));
        BtnAsignacionContratos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnAsignacionContratos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnAsignacionContratos.setRadius(50);
        BtnAsignacionContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAsignacionContratosMouseClicked(evt);
            }
        });
        add(BtnAsignacionContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 210, 50));

        roundedPanel1.setBackground(new java.awt.Color(227, 245, 255));
        roundedPanel1.setRoundBottomLeft(30);
        roundedPanel1.setRoundBottomRight(30);
        roundedPanel1.setRoundTopLeft(30);
        roundedPanel1.setRoundTopRight(30);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setBackground(new java.awt.Color(236, 245, 250));
        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        roundedPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Horario de inicio");
        roundedPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hora atención");
        roundedPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jTextField7.setBackground(new java.awt.Color(236, 245, 250));
        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        jTextField7.setText("jTextField1");
        roundedPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 250, 30));

        BtnAgregar.setBackground(new java.awt.Color(227, 245, 255));
        BtnAgregar.setForeground(new java.awt.Color(83, 83, 83));
        BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus +_20px.png"))); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.setToolTipText("");
        BtnAgregar.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnAgregar.setColor(new java.awt.Color(144, 224, 239));
        BtnAgregar.setColorClick(new java.awt.Color(0, 204, 204));
        BtnAgregar.setColorOver(new java.awt.Color(0, 204, 204));
        BtnAgregar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnAgregar.setRadius(40);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        roundedPanel1.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 50));

        BtnActualizar.setBackground(new java.awt.Color(227, 245, 255));
        BtnActualizar.setForeground(new java.awt.Color(83, 83, 83));
        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_20px.png"))); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setToolTipText("");
        BtnActualizar.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnActualizar.setColor(new java.awt.Color(144, 224, 239));
        BtnActualizar.setColorClick(new java.awt.Color(0, 204, 204));
        BtnActualizar.setColorOver(new java.awt.Color(0, 204, 204));
        BtnActualizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnActualizar.setRadius(40);
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        roundedPanel1.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 130, 50));

        BtnLimpiarCampos1.setBackground(new java.awt.Color(227, 245, 255));
        BtnLimpiarCampos1.setForeground(new java.awt.Color(83, 83, 83));
        BtnLimpiarCampos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/broom_20px.png"))); // NOI18N
        BtnLimpiarCampos1.setText("Limpiar Campos");
        BtnLimpiarCampos1.setToolTipText("");
        BtnLimpiarCampos1.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnLimpiarCampos1.setColor(new java.awt.Color(144, 224, 239));
        BtnLimpiarCampos1.setColorClick(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos1.setColorOver(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnLimpiarCampos1.setRadius(40);
        BtnLimpiarCampos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLimpiarCampos1MouseClicked(evt);
            }
        });
        roundedPanel1.add(BtnLimpiarCampos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 160, 50));

        jTextField3.setBackground(new java.awt.Color(236, 245, 250));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        roundedPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 250, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hora final");
        roundedPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(236, 245, 250));
        jComboBox4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roundedPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 250, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Empleado");
        roundedPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 620, 260));

        roundedPanel2.setBackground(new java.awt.Color(227, 245, 255));
        roundedPanel2.setRoundBottomLeft(30);
        roundedPanel2.setRoundBottomRight(30);
        roundedPanel2.setRoundTopLeft(30);
        roundedPanel2.setRoundTopRight(30);
        roundedPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Codigo de plan");
        roundedPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextField4.setBackground(new java.awt.Color(236, 245, 250));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        roundedPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 30));

        BtnAgregar2.setBackground(new java.awt.Color(227, 245, 255));
        BtnAgregar2.setForeground(new java.awt.Color(83, 83, 83));
        BtnAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus +_20px.png"))); // NOI18N
        BtnAgregar2.setText("Agregar");
        BtnAgregar2.setToolTipText("");
        BtnAgregar2.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnAgregar2.setColor(new java.awt.Color(144, 224, 239));
        BtnAgregar2.setColorClick(new java.awt.Color(0, 204, 204));
        BtnAgregar2.setColorOver(new java.awt.Color(0, 204, 204));
        BtnAgregar2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnAgregar2.setRadius(40);
        BtnAgregar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregar2MouseClicked(evt);
            }
        });
        roundedPanel2.add(BtnAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 50));

        BtnActualizar2.setBackground(new java.awt.Color(227, 245, 255));
        BtnActualizar2.setForeground(new java.awt.Color(83, 83, 83));
        BtnActualizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_20px.png"))); // NOI18N
        BtnActualizar2.setText("Actualizar");
        BtnActualizar2.setToolTipText("");
        BtnActualizar2.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnActualizar2.setColor(new java.awt.Color(144, 224, 239));
        BtnActualizar2.setColorClick(new java.awt.Color(0, 204, 204));
        BtnActualizar2.setColorOver(new java.awt.Color(0, 204, 204));
        BtnActualizar2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnActualizar2.setRadius(40);
        BtnActualizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizar2MouseClicked(evt);
            }
        });
        roundedPanel2.add(BtnActualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 130, 50));

        jComboBox5.setBackground(new java.awt.Color(236, 245, 250));
        jComboBox5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roundedPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 250, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Horario de inicio");
        roundedPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        BtnLimpiarCampos3.setBackground(new java.awt.Color(227, 245, 255));
        BtnLimpiarCampos3.setForeground(new java.awt.Color(83, 83, 83));
        BtnLimpiarCampos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/broom_20px.png"))); // NOI18N
        BtnLimpiarCampos3.setText("Limpiar Campos");
        BtnLimpiarCampos3.setToolTipText("");
        BtnLimpiarCampos3.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnLimpiarCampos3.setColor(new java.awt.Color(144, 224, 239));
        BtnLimpiarCampos3.setColorClick(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos3.setColorOver(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnLimpiarCampos3.setRadius(40);
        BtnLimpiarCampos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLimpiarCampos3MouseClicked(evt);
            }
        });
        roundedPanel2.add(BtnLimpiarCampos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 160, 50));

        jComboBox6.setBackground(new java.awt.Color(236, 245, 250));
        jComboBox6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roundedPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 250, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Empleado");
        roundedPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 630, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizarMouseClicked

    private void BtnLimpiarCampos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarCampos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarCampos1MouseClicked

    private void BtnAgregar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregar2MouseClicked

    private void BtnActualizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizar2MouseClicked

    private void BtnLimpiarCampos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarCampos3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarCampos3MouseClicked

    private void BtnHorarioEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHorarioEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHorarioEmpleadoMouseClicked

    private void BtnPlanesEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPlanesEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPlanesEmpleadoMouseClicked

    private void BtnHorarioAplicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHorarioAplicacionesMouseClicked
        // TODO add your handling code here:
        FrmHorarioEmpleados next = new FrmHorarioEmpleados();
        next.setVisible(true);
    }//GEN-LAST:event_BtnHorarioAplicacionesMouseClicked

    private void BtnAsignacionContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAsignacionContratosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAsignacionContratosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Validaciones.BotonRedondo BtnActualizar;
    private Validaciones.BotonRedondo BtnActualizar2;
    private Validaciones.BotonRedondo BtnAgregar;
    private Validaciones.BotonRedondo BtnAgregar2;
    private Validaciones.BotonRedondo BtnAsignacionContratos;
    private Validaciones.BotonRedondo BtnHorarioAplicaciones;
    private Validaciones.BotonRedondo BtnHorarioEmpleado;
    private Validaciones.BotonRedondo BtnLimpiarCampos1;
    private Validaciones.BotonRedondo BtnLimpiarCampos3;
    private Validaciones.BotonRedondo BtnPlanesEmpleado;
    private javax.swing.JLabel LblTItulo;
    private javax.swing.JLabel LblTItulo1;
    private jtextfieldround.JTextFieldRound TxtBuscar;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private Validaciones.RoundedPanel roundedPanel1;
    private Validaciones.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
}
