/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author pc
 */
public class JPanlImplementosEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form JPanlPlanesTrabajo
     */
    public JPanlImplementosEmpleados() {
        initComponents();
        FlatLightLaf.setup();
        try {
             UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        UIManager.put( "Button.arc", 999 );
        UIManager.put( "Component.arc", 999 );
        UIManager.put( "ProgressBar.arc", 999 );
        UIManager.put( "TextComponent.arc", 999 );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtBuscar = new jtextfieldround.JTextFieldRound();
        jLabel7 = new javax.swing.JLabel();
        LblTItulo = new javax.swing.JLabel();
        LblTItulo1 = new javax.swing.JLabel();
        BtnReporteImplemento = new Validaciones.BotonRedondo();
        roundedPanel1 = new Validaciones.RoundedPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BtnAgregar = new Validaciones.BotonRedondo();
        BtnActualizar = new Validaciones.BotonRedondo();
        BtnLimpiarCampos1 = new Validaciones.BotonRedondo();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        roundedPanel2 = new Validaciones.RoundedPanel();
        BtnAgregar1 = new Validaciones.BotonRedondo();
        BtnActualizar1 = new Validaciones.BotonRedondo();
        BtnLimpiarCampos2 = new Validaciones.BotonRedondo();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtBuscar.setText("Ingrese el nombre del usuario a buscar");
        TxtBuscar.setBackground(new java.awt.Color(236, 245, 250));
        TxtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 570, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search_20px.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, 30));

        LblTItulo.setBackground(new java.awt.Color(83, 83, 83));
        LblTItulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LblTItulo.setForeground(new java.awt.Color(0, 0, 0));
        LblTItulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblTItulo.setText("Implementos de empleados");
        LblTItulo.setToolTipText("");
        LblTItulo.setPreferredSize(new java.awt.Dimension(100, 19));
        add(LblTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, -1));

        LblTItulo1.setBackground(new java.awt.Color(83, 83, 83));
        LblTItulo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LblTItulo1.setForeground(new java.awt.Color(0, 0, 0));
        LblTItulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblTItulo1.setText("Implementos medicos");
        LblTItulo1.setToolTipText("");
        LblTItulo1.setPreferredSize(new java.awt.Dimension(100, 19));
        add(LblTItulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, -1));

        BtnReporteImplemento.setBackground(new java.awt.Color(144, 224, 239));
        BtnReporteImplemento.setForeground(new java.awt.Color(83, 83, 83));
        BtnReporteImplemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Check Circle_20px.png"))); // NOI18N
        BtnReporteImplemento.setText("Reporte de implementos");
        BtnReporteImplemento.setToolTipText("");
        BtnReporteImplemento.setBorderColor(new java.awt.Color(255, 255, 255));
        BtnReporteImplemento.setColor(new java.awt.Color(144, 224, 239));
        BtnReporteImplemento.setColorClick(new java.awt.Color(0, 204, 204));
        BtnReporteImplemento.setColorOver(new java.awt.Color(0, 204, 204));
        BtnReporteImplemento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnReporteImplemento.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnReporteImplemento.setRadius(50);
        BtnReporteImplemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnReporteImplementoMouseClicked(evt);
            }
        });
        add(BtnReporteImplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 210, 50));

        roundedPanel1.setBackground(new java.awt.Color(227, 245, 255));
        roundedPanel1.setRoundBottomLeft(30);
        roundedPanel1.setRoundBottomRight(30);
        roundedPanel1.setRoundTopLeft(30);
        roundedPanel1.setRoundTopRight(30);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBackground(new java.awt.Color(236, 245, 250));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        roundedPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Id emplemento");
        roundedPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        BtnAgregar.setBackground(new java.awt.Color(144, 224, 239));
        BtnAgregar.setForeground(new java.awt.Color(83, 83, 83));
        BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus +_20px.png"))); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.setToolTipText("");
        BtnAgregar.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnAgregar.setColor(new java.awt.Color(144, 224, 239));
        BtnAgregar.setColorClick(new java.awt.Color(0, 204, 204));
        BtnAgregar.setColorOver(new java.awt.Color(0, 204, 204));
        BtnAgregar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnAgregar.setRadius(40);
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        roundedPanel1.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 50));

        BtnActualizar.setBackground(new java.awt.Color(144, 224, 239));
        BtnActualizar.setForeground(new java.awt.Color(83, 83, 83));
        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_20px.png"))); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setToolTipText("");
        BtnActualizar.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnActualizar.setColor(new java.awt.Color(144, 224, 239));
        BtnActualizar.setColorClick(new java.awt.Color(0, 204, 204));
        BtnActualizar.setColorOver(new java.awt.Color(0, 204, 204));
        BtnActualizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnActualizar.setRadius(40);
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        roundedPanel1.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, 50));

        BtnLimpiarCampos1.setBackground(new java.awt.Color(144, 224, 239));
        BtnLimpiarCampos1.setForeground(new java.awt.Color(83, 83, 83));
        BtnLimpiarCampos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/broom_20px.png"))); // NOI18N
        BtnLimpiarCampos1.setText("Limpiar Campos");
        BtnLimpiarCampos1.setToolTipText("");
        BtnLimpiarCampos1.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnLimpiarCampos1.setColor(new java.awt.Color(144, 224, 239));
        BtnLimpiarCampos1.setColorClick(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos1.setColorOver(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnLimpiarCampos1.setRadius(40);
        BtnLimpiarCampos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLimpiarCampos1MouseClicked(evt);
            }
        });
        roundedPanel1.add(BtnLimpiarCampos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 160, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hora final");
        roundedPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(236, 245, 250));
        jComboBox4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roundedPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 250, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Implementos medicos");
        roundedPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Empleado");
        roundedPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jComboBox7.setBackground(new java.awt.Color(236, 245, 250));
        jComboBox7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBox7.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roundedPanel1.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, -1));
        roundedPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 250, -1));

        add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 630, 230));

        roundedPanel2.setBackground(new java.awt.Color(227, 245, 255));
        roundedPanel2.setRoundBottomLeft(30);
        roundedPanel2.setRoundBottomRight(30);
        roundedPanel2.setRoundTopLeft(30);
        roundedPanel2.setRoundTopRight(30);
        roundedPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAgregar1.setBackground(new java.awt.Color(144, 224, 239));
        BtnAgregar1.setForeground(new java.awt.Color(83, 83, 83));
        BtnAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus +_20px.png"))); // NOI18N
        BtnAgregar1.setText("Agregar");
        BtnAgregar1.setToolTipText("");
        BtnAgregar1.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnAgregar1.setColor(new java.awt.Color(144, 224, 239));
        BtnAgregar1.setColorClick(new java.awt.Color(0, 204, 204));
        BtnAgregar1.setColorOver(new java.awt.Color(0, 204, 204));
        BtnAgregar1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnAgregar1.setRadius(40);
        BtnAgregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregar1MouseClicked(evt);
            }
        });
        roundedPanel2.add(BtnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 130, 50));

        BtnActualizar1.setBackground(new java.awt.Color(144, 224, 239));
        BtnActualizar1.setForeground(new java.awt.Color(83, 83, 83));
        BtnActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh_20px.png"))); // NOI18N
        BtnActualizar1.setText("Actualizar");
        BtnActualizar1.setToolTipText("");
        BtnActualizar1.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnActualizar1.setColor(new java.awt.Color(144, 224, 239));
        BtnActualizar1.setColorClick(new java.awt.Color(0, 204, 204));
        BtnActualizar1.setColorOver(new java.awt.Color(0, 204, 204));
        BtnActualizar1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnActualizar1.setRadius(40);
        BtnActualizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizar1MouseClicked(evt);
            }
        });
        roundedPanel2.add(BtnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 130, 50));

        BtnLimpiarCampos2.setBackground(new java.awt.Color(144, 224, 239));
        BtnLimpiarCampos2.setForeground(new java.awt.Color(83, 83, 83));
        BtnLimpiarCampos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/broom_20px.png"))); // NOI18N
        BtnLimpiarCampos2.setText("Limpiar Campos");
        BtnLimpiarCampos2.setToolTipText("");
        BtnLimpiarCampos2.setBorderColor(new java.awt.Color(227, 245, 255));
        BtnLimpiarCampos2.setColor(new java.awt.Color(144, 224, 239));
        BtnLimpiarCampos2.setColorClick(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos2.setColorOver(new java.awt.Color(0, 204, 204));
        BtnLimpiarCampos2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnLimpiarCampos2.setRadius(40);
        BtnLimpiarCampos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLimpiarCampos2MouseClicked(evt);
            }
        });
        roundedPanel2.add(BtnLimpiarCampos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 160, 50));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Id emplemento");
        roundedPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextField5.setBackground(new java.awt.Color(236, 245, 250));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        roundedPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 30));

        jComboBox8.setBackground(new java.awt.Color(236, 245, 250));
        jComboBox8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBox8.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roundedPanel2.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Empleado");
        roundedPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Fecha de compra");
        roundedPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        roundedPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 250, -1));

        jComboBox9.setBackground(new java.awt.Color(236, 245, 250));
        jComboBox9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBox9.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roundedPanel2.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 250, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Estado del implemento");
        roundedPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Tipo de implementos");
        roundedPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        jComboBox10.setBackground(new java.awt.Color(236, 245, 250));
        jComboBox10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jComboBox10.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roundedPanel2.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 140, -1));

        jTextField8.setBackground(new java.awt.Color(236, 245, 250));
        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        roundedPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 110, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Precio");
        roundedPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jTextField9.setBackground(new java.awt.Color(236, 245, 250));
        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(0, 0, 0));
        roundedPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 250, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Emplemento medico");
        roundedPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 850, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizarMouseClicked

    private void BtnLimpiarCampos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarCampos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarCampos1MouseClicked

    private void BtnReporteImplementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnReporteImplementoMouseClicked

        // TODO add your handling code here:
        FrmReporteImplementos next = new FrmReporteImplementos();
        next.setVisible(true);
    }//GEN-LAST:event_BtnReporteImplementoMouseClicked

    private void BtnAgregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregar1MouseClicked

    private void BtnActualizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizar1MouseClicked

    private void BtnLimpiarCampos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLimpiarCampos2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarCampos2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Validaciones.BotonRedondo BtnActualizar;
    private Validaciones.BotonRedondo BtnActualizar1;
    private Validaciones.BotonRedondo BtnAgregar;
    private Validaciones.BotonRedondo BtnAgregar1;
    private Validaciones.BotonRedondo BtnLimpiarCampos1;
    private Validaciones.BotonRedondo BtnLimpiarCampos2;
    private Validaciones.BotonRedondo BtnReporteImplemento;
    private javax.swing.JLabel LblTItulo;
    private javax.swing.JLabel LblTItulo1;
    private jtextfieldround.JTextFieldRound TxtBuscar;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private Validaciones.RoundedPanel roundedPanel1;
    private Validaciones.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
}
